# SonarCloud Automatic Analysis Configuration for RETHINK-Realtime
sonar.sources=web/src,worker/src
sonar.tests=web/test,worker/test
sonar.exclusions=dist,node_modules,worker/migrations
sonar.cpd.exclusions=web/test,worker/test,worker/migrations
