name = "rethink-realtime-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "rethink-realtime-hmac-sha256-kiosk-booth-production-salt-2026-secure"

[[d1_databases]]
binding = "DB"
database_name = "rethink-realtimevoice"
database_id = "7e0b0d07-1888-4a37-adbf-8c33c2db314a"
